Extended scripting interfaces and tests.
Implemented scripting APIs for opening helix data files
and running other scripts.  Created test cases to show
the behavior.  The APIs are called through a new "rheat"
script variable that refers to an AppMain object.

diff --git a/RNA_HEAT/test/Makefile b/RNA_HEAT/test/Makefile
--- a/RNA_HEAT/test/Makefile
+++ b/RNA_HEAT/test/Makefile
@@ -19,16 +19,27 @@ all: check
 
 # run all tests
 check:
-	@for T in $(shell find 'no_gui_cases' -name '*.t' -type d) ; do \
+	@nfail=0 ; npass=0 ; \
+	for T in $(shell find 'no_gui_cases' -name '*.t' -type d) ; do \
 		echo "=============================" ; \
 		echo "  $$T" ; \
 		echo "=============================" ; \
 		echo $${T}/run_test.js ; \
-		$${T}/run_test.js  && echo "Test PASSED." ; \
-	done
-	@echo "============================="
-	@echo "  Test iterations complete."
-	@echo "============================="
+		$${T}/run_test.js ; \
+		if [ "x$$?" = "x0" ] ; then \
+		    echo "Test PASSED." ; \
+		    npass=$$((npass+1)) ; \
+		else \
+		    echo "!!!!!!!!!!!!!!!!!!!" ; \
+		    echo "!!! Test FAILED !!!" ; \
+		    echo "!!!!!!!!!!!!!!!!!!!" ; \
+		    nfail=$$((nfail+1)) ; \
+		fi ; \
+	done ; \
+	echo "=============================" ; \
+	echo "  Test iterations complete." ; \
+	echo "  FAILED: $$nfail    OK: $$npass" ; \
+	echo "============================="
 
 # remove temporary test results
 clean:
